---
- hosts: localhost
  become: yes
  vars:
    - dotfiles_repo: git@github.com:mich-murphy/.dotfiles.git
    - source_key: "./.ssh/id_rsa"
    - dest_key: "home/mm/.ssh/id_rsa"
    - username: mm

  pre_tasks:
  - name: system update
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes
  - name: install AUR ansible module
    shell: ansible-galaxy collection install kewlfft.aur

  tasks:
  - include_tasks: tasks/setup.yml
  - include_tasks: tasks/dotfiles.yml
