---
- hosts: localhost
  become: yes
  vars:
    - dotfiles_repo: git@github.com:mich-murphy/.dotfiles.git
    - source_key: "./.ssh/id_rsa"
    - username: mm
    - dest_key: "/home/{{ username }}/.ssh/id_rsa"
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"

  pre_tasks:
  - name: system update
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes

  tasks:
  - include_tasks: tasks/setup.yml
  - include_tasks: tasks/ssh.yml
  - include_tasks: tasks/dotfiles.yml
  - include_tasks: tasks/systemd.yml
