---
- hosts: localhost
  become: true
  vars:
    - dotfiles_repo: git@github.com:mich-murphy/.dotfiles.git
    - source_key: "./.ssh/id_rsa"
    - dest_key: "home/mm/.ssh/id_rsa"
    - user: mm

  pre_tasks:
  - name: System update
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes

  tasks:
  - include_tasks: tasks/setup.yml
  - include_tasks: tasks/dotfiles.yml
