---
- name: install yay
  aur:
    name: yay
    user: "{{ username }}"

- name: install AUR packages
  aur:
    name:
      - python-clickgen
      - bibata-cursor-theme
      - brave-bin
      - brillo
      - cava
      - mkpasswd
      - picom-git
      - spotify-tui
      - spotifyd-full-git
      - nvm
      - nsxiv
      - auto-cpufreq
    user: "{{ username }}"

- name: configure spotifyd.service
  blockinfile:
   path: /etc/systemd/user/spotifyd.service
   create: yes
   block: |
     [Unit]
     Description=A spotify playing daemon
     Documentation=https://github.com/Spotifyd/spotifyd
     Wants=sound.target
     After=sound.target
     Wants=network-online.target
     After=network-online.target
     
     [Service]
     ExecStart=/usr/bin/spotifyd --no-daemon
     Restart=always
     RestartSec=12

     [Install]
     WantedBy=default.target
