---
- name: install requirements from package manager
  tags: dotfiles
  package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - kitty
      - i3-gaps
      - i3lock
      - autorandr
      - feh
      - tmux
      - tmuxp
      - stow
      - scrot
      - rofi
      - rofi-calc
      - redshift
      - ranger
      - python
      - python-pip
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
      - libnotify
      - dunst
      - fd
      - diff-so-fancy
      - exa
      - bat
      - ripgrep
      - firefox
      - ufw
      - iptables
      - fzf
      - neovim
      - python-neovim
      - nodejs
      - yarn
      - zathura-pdf-mupdf
      - openssh
      - tree
    state: present
      
- name: change "{{ username }}"'s shell to zsh
  tags: dotfiles
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: install yay
  aur:
    name: yay
    user: aur_builder

- name: install AUR packages
  aur:
    name:
      - devour
      - autotiling-git
      - python-clickgen
      - bibata-cursor-theme
      - brave-bin
      - cava
      - mkpasswd
      - picom-git
      - rofi-greenclip
      - rofi-power-menu
      - rxfetch
      - spotify-tui
      - spotifyd-full-git
      - ttf-material-design-icons
      - nvm
      - vscodium
      - vscodium-marketplace
      - polybar
      - nsxiv
      - auto-cpufreq
    user: aur_builder

- name: clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: stow dotfiles
  shell: cd "/home/{{ username }}/.dotfiles" && stow */

# - name: install starship prompt
#   become_user: "{{ username }}"
#   shell: curl -sS https://starship.rs/install.sh | sh

