---
- name: change "{{ username }}"'s shell to zsh
  tags: dotfiles
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: remove existing cava directory
  shell: rm -r "/home/{{ username }}/.config/cava"

- name: stow dotfiles
  shell: cd "/home/{{ username }}/.dotfiles" && stow */

- name: download starship install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /opt/starshipinstall
    mode: 0755

- name: install starship prompt
  shell: ./opt/starshipinstall

