---
- name: install requirements from package manager
  tags: dotfiles
  package: 
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - kitty
      - i3-gaps
      - i3lock
      - autorandr
      - feh
      - tmux
      - tmuxp
      - stow
      - scrot
      - rofi
      - rofi-calc
      - redshift
      - ranger
      - python
      - python-pip
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
      - libnotify
      - dunst
      - fd
      - diff-so-fancy
      - exa
      - ripgrep
      - firefox
      - firewalld
      - fzf
      - neovim
      - python-neovim
      - nodejs
      - yarn
    state: present
      
- name: change "{{ username }}"'s shell to zsh
  tags: dotfiles
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

# - name: install aur requirements
#   package:
#     name:
#       - binutils
#       - which
#       - fakeroot
#       - gcc
#       - cmake
#       - make
#     state: present

- name: install AUR packages
  aur:
    name: 
      - polybar
      - yay
    user: "{{ username }}"
    # dir: $XDG_CONFIG_HOME/local/bin
