---
- name: install requirements from package manager
  become_user: "{{ user }}"
  tags: dotfiles
  package: 
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - kitty
      - i3-gaps
      - i3lock
      - autorandr
      - feh
      - tmux
      - tmuxp
      - stow
      - scrot
      - rofi
      - rofi-calc
      - redshift
      - ranger
      - python
      - python-pip
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
      - libnotify
      - dunst
      - fd
      - diff-so-fancy
      - exa
      - ripgrep
      - firefox
      - firewalld
      - fzf
      - neovim
      - python-neovim
      - nodejs
      - yarn
    state: present
      
- name: change shell
  become_user: "{{ user }}"
  tags: dotfiles
  shell: chsh -s /usr/sbin/zsh

- name: clone yay repo
  become: true
  become_user: "{{ user }}"
  tags: dotfiles
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "/home/{{ user }}/git/yay"
    clone: yes

- name: make yay package
  become_user: "{{ user }}"
  tags: dotfiles
  shell: "cd /home/{{ user }}/git/yay/ && makepkg -si"
