---
- name: install requirements from package manager
  tags: dotfiles
  package: 
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - kitty
      - i3-gaps
      - i3lock
      - autorandr
      - feh
      - tmux
      - tmuxp
      - stow
      - scrot
      - rofi
      - rofi-calc
      - redshift
      - ranger
      - python
      - python-pip
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
      - libnotify
      - dunst
      - fd
      - diff-so-fancy
      - exa
      - ripgrep
      - firefox
      - firewalld
      - fzf
      - neovim
      - python-neovim
      - nodejs
      - yarn
    state: present
      
- name: change "{{ username }}"'s shell to zsh
  tags: dotfiles
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become_user: aur_builder

- name: install AUR packages
  kewlfft.aur.aur:
    use: yay
    name: 
      - devour
      - autotiling-git
      - bibata-cursor-theme
      - brave-bin
      - cava
      - mkpasswd
      - picom-git
      - rofi-greenclip
      - rofi-power-menu
      - rxfetch
      - spotify-tui
      - spotifyd-full-git
      - ttf-material-design-icons
      - vscodium
      - vscodium-marketplace
      - polybar-git
      - nsxiv
    state: present
