---
- name: change "{{ username }}"'s shell to zsh
  tags: dotfiles
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: stow dotfiles
  shell: cd "/home/{{ username }}/.dotfiles" && stow */
