---
- name: install requirements from package manager
  tags: dotfiles
  package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - starship
      - kitty
      - autorandr
      - feh
      - tmux
      - tmuxp
      - stow
      - scrot
      - redshift
      - python
      - python-pip
      - pamixer
      - libnotify
      - dunst
      - fd
      - diff-so-fancy
      - exa
      - bat
      - ripgrep
      - fzf
      - neovim
      - python-neovim
      - nodejs
      - yarn
      - zathura-pdf-mupdf
      - openssh
      - tree
      - wmctrl
      - graphicsmagick
      - cargo
      - wget
      - btop
      - thunar
    state: present
