---
- name: create "{{ username }}" user
  tags: setup
  user:
    name: "{{ username }}"
    password: "{{ user_password|password_hash('sha512') }}"
    groups: wheel,video
    shell: /bin/bash
    create_home: yes
    home: "/home/{{ username }}"

- name: create Downloads folder in "{{ username }}" home
  tags: setup
  file:
    path: "/home/{{ username }}/Downloads"
    state: directory

- name: create Documents folder in "{{ username }}" home
  tags: setup
  file:
    path: "/home/{{ username }}/Documents"
    state: directory

- name: give "{{ username }}" sudo priviliges
  tags: setup
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: allow "{{ username }}" to change backlight
  tags: setup
  blockinfile:
   path: /etc/udev/rules.d/backlight.rules
   create: yes
   block: |
     RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness"
     RUN+="/bin/chmod g+w /sys/class/backlight/intel_backlight/brightness"

- name: install core system packages
  tags: setup
  package:
    name:
      - man
      - man-pages
      - xorg
      - xorg-xinit
      - openssh
      - xsel
      - udiskie
      - lxappearance
      - xcape
      - unzip
      - polkit
      - networkmanager
      - alsa-utils
    state: present

- name: set timezone
  shell: timedatectl set-timezone Australia/Melbourne
