---
- name: Create the `aur_builder` user
  user:
    name: aur_builder
    comment: "AUR manager"
    home: /var/lib/aur_builder
    shell: /bin/nologin
    system: yes

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: create "{{ username }}" user
  tags: setup
  user:
    name: "{{ username }}"
    password: "{{ user_password|password_hash('sha512') }}"
    groups: wheel
    shell: /bin/bash
    create_home: yes

- name: give "{{ username }}" sudo priviliges
  tags: setup
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  tags: setup
  package:
    name:
      - man
      - man-pages
      - xorg
      - xorg-xinit
      - openssh
      - xsel
      - udiskie
      - lxappearance
      - xcape
      - unzip
      - polkit
      - networkmanager
    state: present
