---
- name: install sudo and reflector
  tags: setup
  pacman:
    name: 
      - sudo
      - reflector
    state: present

- name: update reflector config
  lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    line: '--country "Australia"'

- name: enable reflector.timer
  systemd:
    name: reflector.timer
    enabled: yes
    state: started

- name: enable reflector.service
  systemd:
    name: reflector.service
    enabled: yes
    state: started

- name: create the `aur_builder` user
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: create "{{ username }}" user
  tags: setup
  user:
    name: "{{ username }}"
    password: $6$jkw3ST8ONcMgA8Zl$weIYelXXNMCos5sNEzbKPnaBZv62LQF.NXR1H.N/AgG.IR6YFcvTU9SeqGYYaUU7r1IYGVxGLdjgIyekPi4XR.
    groups: wheel
    shell: /bin/bash
    create_home: yes

- name: give "{{ username }}" sudo priviliges
  tags: setup
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  tags: setup
  pacman:
    name:
      - man
      - man-pages
      - xorg
      - xorg-xinit
      - openssh
      - xsel
      - udiskie
      - lxappearance
      - xcape
      - unzip
      - polkit
    state: present
