---
- name: install sudo
  tags: setup
  pacman:
    name: 
      - sudo
    state: present

- name: create "{{ username }}" user
  tags: setup
  user:
    name: "{{ username }}"
    password: $6$jkw3ST8ONcMgA8Zl$weIYelXXNMCos5sNEzbKPnaBZv62LQF.NXR1H.N/AgG.IR6YFcvTU9SeqGYYaUU7r1IYGVxGLdjgIyekPi4XR.
    groups: wheel
    shell: /bin/bash
    create_home: yes

- name: give "{{ username }}" sudo priviliges
  tags: setup
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  tags: setup
  pacman:
    name:
      - man
      - man-pages
      - xorg
      - xorg-xinit
      - openssh
      - xsel
      - udiskie
      - lxappearance
      - xcape
      - unzip
      - polkit
    state: present
