---
- name: ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: change .ssh/ ownership
  shell: sudo chown "{{ username }}":wheel "/home/{{ username }}/.ssh"

- name: set authorized key took from file
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "/home/{{ username }}/.ssh/id_rsa.pub"
