---
- name: ensure .ssh directory exists.
  become_user: "{{ username }}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: install ssh key
  become_user: "{{ username }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: install ssh key public
  become_user: "{{ username }}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: set authorized key from file
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
