---
- name: enable ufw service
  systemd:
    name: ufw.service
    state: started
    enabled: yes

- name: enable iptables service
  systemd:
    name: iptables.service
    enabled: yes

- name: enable auto-cpufreq service
  systemd:
    name: auto-cpufreq.service
    state: started
    enabled: yes

- name: enable spotifyd service
  systemd:
    name: spotifyd.service
    state: started
    enabled: yes
    scope: user
